#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

eww open bar

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Alacritty desktop='^1'
bspc rule -a firefox desktop='^2'
bspc rule -a Code desktop='^3'
bspc rule -a discord desktop='^9'
bspc rule -a TelegramDesktop desktop='^10'

# autostart applications
dex -a

feh --bg-fill --randomize ~/.config/wallpaper

picom &
